// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobInput struct {
	JobID          string  `json:"JobID"`
	Status         string  `json:"status"`
	Duration       string  `json:"duration"`
	QueuedDuration string  `json:"queued_duration"`
	Title          *string `json:"title"`
	UserID         *string `json:"userID"`
	CreatedAt      *string `json:"createdAt"`
}

type Jobs struct {
	ID             string  `json:"id"`
	JobID          string  `json:"JobID"`
	Title          *string `json:"title"`
	Status         string  `json:"status"`
	Duration       string  `json:"duration"`
	QueuedDuration string  `json:"queued_duration"`
	User           *User   `json:"user"`
}

type User struct {
	UserID    *string `json:"userID"`
	CreatedAt *string `json:"createdAt"`
}
