version: '3.6'
services:
  api-gateway:
    build:
      context: "./"
      dockerfile: Dockerfile
      target: development
    networks:
      - ship
    environment:
      APP_ENV: development
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "4000:4000"

networks:
  ship:
    name: ship_network